In [258]:
import numpy as np
import numpy.random as np_rand
import random

from tqdm import tqdm_notebook as tqdm
import sys

In [271]:
def createRandomChess(N):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
    return chess

In [246]:
def heuristic(chess):
    (x,y) = np.where(chess)
    queens = list(zip(x,y))
    totalAttackingPairs = 0
    for i in range(0, len(queens) - 1):
        (x1, y1)= queens[i]
        for j in range(i+1, len(queens)):
            (x2, y2)= queens[j]
            if(x1 == x2 or y1 == y2):
                totalAttackingPairs = totalAttackingPairs + 1
            elif(abs(x1 - x2) == abs(y1 - y2)):
                totalAttackingPairs = totalAttackingPairs + 1
    return totalAttackingPairs

In [293]:
def steepestAscent(chess):
    currentChess = np.array(chess)
    currentHeuristic = heuristic(currentChess)
    steps = 0

    print("Begin")
    while(True):
        currentHeuristic = heuristic(currentChess)
        tempChess = np.array(currentChess)
        tempHeuristic = currentHeuristic
        print(tempChess)
        print("Heuristic:", tempHeuristic)
        if(currentHeuristic == 0):
            break
        steps = steps + 1
        for i in range(0, N):
            row = currentChess[i]
            currentPosition = np.where(row)
            for pos in [p for p in range(0, N) if p != currentPosition]:
                nextChess = np.array(currentChess)
                nextChess[i][currentPosition] = 0
                nextChess[i][pos] = 1
                nextHeuristic = heuristic(nextChess)
                if(nextHeuristic < tempHeuristic):
                    tempChess = np.array(nextChess)
                    tempHeuristic = nextHeuristic
        if(tempHeuristic >= currentHeuristic):
            break
        currentChess = np.array(tempChess)

    return (currentChess, steps)

In [294]:
N=8
count = 10

# Steepest Ascent Hill 
success = 0
failure = 0
successSteps = 0
failureSteps = 0
print("Steepest Ascent...... simulation: -")
for sample in tqdm(range(0, count)):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
#     print("Start", chess)
    (solvedChess, steps) = steepestAscent(chess)
    if(heuristic(solvedChess) == 0):
        success = success + 1
        successSteps = successSteps + steps
    else:
        failure = failure + 1
        failureSteps = failureSteps + steps

if(success > 0):
    print("Success states: ", success)
    print("Success percentage: ", success/5, "%")
    print("Average success steps: ", successSteps//(success))
else:
    print("No Success")
if(failure > 0):
    print("Failure states: ", failure)
    print("Failure percentage: ", failure/5, "%")
    print("Average failure steps: ", failureSteps//(failure))
else:
    print("No Failure")
print()

Steepest Ascent...... simulation: -


Begin
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 5
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 0
Begin
[[0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 6
[[0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]]
Heuri

In [248]:
def contains(sideways, chess):
    for c in sideways:
        if(np.array_equal(c, chess)):
            return True
    return False

In [250]:
def containsElement(arr, ele):
    for row in arr:
        exists = np.all(np.equal(row, ele))
        if(exists):
            return True
    return False

In [298]:
def steepestAscentWithSideways(chess, sidewaysThreshold):
    currentChess = np.array(chess)
    currentHeuristic = heuristic(currentChess)

    sidewaysCounter = sidewaysThreshold
    sidewaysNext = []
    steps = 0

    print("Begin")
    while(True):
        currentHeuristic = heuristic(currentChess)
        tempChess = np.array(currentChess)
        tempHeuristic = currentHeuristic
        sideRequired = True
        print(currentChess)
        print("Heuristic:", tempHeuristic)
        if(currentHeuristic == 0):
            break
        steps = steps + 1
        for i in range(0, N):
            row = currentChess[i]
            currentPosition = np.where(row)[0][0]
            for pos in [p for p in range(0, N) if p != currentPosition]:
                nextChess = np.array(currentChess)
                nextChess[i][currentPosition] = 0
                nextChess[i][pos] = 1
                nextHeuristic = heuristic(nextChess)
                if(nextHeuristic == 0 or nextHeuristic < tempHeuristic):
                    sideRequired = False
                    tempChess = np.array(nextChess)
                    tempHeuristic = nextHeuristic
                if(sideRequired and (nextHeuristic == tempHeuristic) and (not containsElement(sidewaysNext, nextChess))):
                    tempChess = np.array(nextChess)
                    tempHeuristic = nextHeuristic
                    sidewaysNext.append(nextChess)
        if(tempHeuristic == 0):
            currentChess = np.array(tempChess)
            break
        if(tempHeuristic == currentHeuristic):
            if(sidewaysCounter == 0 or len(sidewaysNext) == 0):
                break
            else:
                if(sidewaysCounter > 0):
                    sidewaysCounter = sidewaysCounter - 1
                currentChess = sidewaysNext.pop(np.random.randint(0, len(sidewaysNext)))
                sidewaysNext = []
        elif(tempHeuristic < currentHeuristic):
            sidewaysCounter = sidewaysThreshold
            sidewaysNext = []
            currentChess = np.array(tempChess)

    return (currentChess, steps)

In [299]:
N=8
count = 10

# Steepest Ascent Hill 
success = 0
failure = 0
successSteps = 0
failureSteps = 0
print("Steepest Ascent...... simulation: -")
for sample in tqdm(range(0, count)):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
#     print("Start", chess)
    (solvedChess, steps) = steepestAscentWithSideways(chess, 100)
    if(heuristic(solvedChess) == 0):
        success = success + 1
        successSteps = successSteps + steps
    else:
        failure = failure + 1
        failureSteps = failureSteps + steps

if(success > 0):
    print("Success states: ", success)
    print("Success percentage: ", success/5, "%")
    print("Average success steps: ", successSteps//(success))
else:
    print("No Success")
if(failure > 0):
    print("Failure states: ", failure)
    print("Failure percentage: ", failure/5, "%")
    print("Average failure steps: ", failureSteps//(failure))
else:
    print("No Failure")
print()

Steepest Ascent...... simulation: -


Begin
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 9
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 5
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 3
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 

 [0 0 1 0 0 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 1
Begin
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 10
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 6
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 4
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 2
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 

 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 

 [0 0 1 0 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]
Heuristic: 1
Begin
[[0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 7
[[0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 4
[[0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 3
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 2
Begin
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1

 [0 0 0 0 1 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 1
Begin
[[0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 7
[[0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 4
[[0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 2
[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 2
[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0

In [279]:
def randomRestartWithoutSideways(chess):
    currentHeuristic = sys.maxsize
    solvedChess = chess
    steps = 0
    restartCount = -1
    while(currentHeuristic != 0):
        (solvedChess, steps) = steepestAscent(chess)
        currentHeuristic = heuristic(solvedChess)
        chess = createRandomChess(chess.shape[0])
        restartCount = restartCount + 1
    return (solvedChess, steps, restartCount)

In [302]:
N=8
count = 10

# Steepest Ascent Hill 
success = 0
failure = 0
successSteps = 0
failureSteps = 0
print("Random Restart with sideways moves allowed...... simulation: -")
for sample in tqdm(range(0, count)):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
#     print("Start", chess)
    (solvedChess, steps, restartCount) = randomRestartWithSideways(chess, 100)
    if(heuristic(solvedChess) == 0):
        success = success + 1
        successSteps = successSteps + steps
    else:
        failure = failure + 1
        failureSteps = failureSteps + steps

if(success > 0):
    print("Average success steps: ", successSteps//(success))
else:
    print("No Success")

print("Average number of restarts required: ", restartCount)

Random Restart with sideways moves allowed...... simulation: -


TypeError: randomRestartWithSideways() takes 1 positional argument but 2 were given

In [303]:
def randomRestartWithSideways(chess, threshold):
    currentHeuristic = sys.maxsize
    solvedChess = chess
    steps = 0
    restartCount = -1
    while(currentHeuristic != 0):
        (solvedChess, steps) = steepestAscentWithSideways(chess, threshold)
        currentHeuristic = heuristic(solvedChess)
        chess = createRandomChess(chess.shape[0])
        restartCount = restartCount + 1
    return (solvedChess, steps, restartCount)

In [304]:
N=8
count = 10

# Steepest Ascent Hill 
success = 0
failure = 0
successSteps = 0
failureSteps = 0
print("Random Restart with sideways moves allowed...... simulation: -")
for sample in tqdm(range(0, count)):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
#     print("Start", chess)
    (solvedChess, steps, restartCount) = randomRestartWithSideways(chess, 100)
    if(heuristic(solvedChess) == 0):
        success = success + 1
        successSteps = successSteps + steps
    else:
        failure = failure + 1
        failureSteps = failureSteps + steps

if(success > 0):
    print("Average success steps: ", successSteps//(success))
else:
    print("No Success")

print("Average number of restarts required: ", restartCount)

Random Restart with sideways moves allowed...... simulation: -


Begin
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 14
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 9
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
Heuristic: 5
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Heuristic:

 [0 0 0 0 0 0 0 1]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 2
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 

 [0 0 0 1 0 0 0 0]]
Heuristic: 2
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
Heuristic: 1
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 

 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 

 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
Heuristic: 1
[[0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 

Heuristic: 2
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 2
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
Heuristic: 1
[[0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]]
Heuristic: 1
Average success steps:  14
Average number of restarts required:  0


In [283]:
N=10

In [285]:
count = 500
success = 0
failure = 0
successSteps = 0
failureSteps = 0
for sample in tqdm(range(0, count)):
    chess = np.zeros((N, N), dtype=np.int0)
    for row in chess:
        row[random.randint(0, N-1)] = 1
#     print("Start", chess)
    (solvedChess, steps) = steepestAscentWithSideways(chess, 100)
    if(heuristic(solvedChess) == 0):
        success = success + 1
        successSteps = successSteps + steps
    else:
        failure = failure + 1
        failureSteps = failureSteps + steps
    #print(solvedChess, heuristic(chess), heuristic(solvedChess))
if(success > 0):
    print(success,successSteps//(success))
else:
    print("No Success")
if(failure > 0):
    print(failure, failureSteps//(failure))
else:
    print("No Failure")

449 30
51 85


In [287]:
chess = np.zeros((N, N), dtype=np.int0)
for row in chess:
    row[random.randint(0, N-1)] = 1

In [288]:
chess

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [289]:
heuristic(chess)

10